# backend/src/main/resources/application.yml
spring:
  application:
    name: todo-backend

  # Database Configuration
  datasource:
    url: jdbc:mariadb://localhost:3307/todoapp
    username: todouser
    password: todopass123
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  # Server Configuration - REMOVED context-path
  server:
    port: 8080

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Logging Configuration
logging:
  level:
    com.coveragex.todobackend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always